---
title: "Debugging Tools - Diagnosing the Problem"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Something's Wrong!

Indications that something's not right:

* `message`: A generic notification/diagnostic message produced by the `message` function; execution of the function continues
* `warning`: An indication that something is wrong but not necessarily fatal; execution of the function continues; generated by the `warning` function
* `error`: An indication that a fatal problem has occurred; execution stops; produced by the `stop` function
* `condition`: A generic concept for indicating that something unexpected can occur; programmers can create their own conditions

How do you know that something is wrong with your function?

* What was your input? How did you call the function?
* What were you expecting? Output, messages, other results?
* What did you get?
* How does what you get differ from what you were expecting?
* Were your expectations correct in the first place?
* Can you reproduce the problem (exactly)?